### ISSUE TITLE
Ignoring JSON fields

### ISSUE THREAD

**Issue by dneykov** [SyncDB/Sync#367] opened 2017-02-09 08:59 UTC
Hi,
I'm wondering is it possible to ignore some of the JSON fields when trying to sync with Core Data.
If there are fields in JSON which are missing my Entity Sync.changes is not working.

Thanks.

**Comment by 3lvis** [comment] 2017-02-10 19:37
@dneykov Hi,

This is a bit strange. If there's a JSON field that is not present in Core Data it should get ignored, if there's a field in Core Data but you don't get it in the JSON then it also gets ignored.

I can try to reproduce your use case but might be useful to clarify the issue.


```json
[
    {
        "id": 1
    }
]
```

```
Core Data
# User
- id: Int
- firstName: String
```


You're saying that my example, won't work, right?

**Comment by dneykov** [comment] 2017-02-10 19:55
Hi,
no my case is the other way. Here is example:
JSON
```
[
  {
    "id": 1,
    "first_name": Daniel,
    "timestamp": 1486756142
  }
]
```

Core Data
```
# User
- id: Int
- firstName: String
```
The example above will not be inserted, if I remove timestamp from the response everything will work. In my exact case there are more fields that should be ignored, this is just basic example.

Thanks.

**Comment by 3lvis** [comment] 2017-02-10 20:05
Thanks! I'll have a look.

**Comment by 3lvis** [comment] 2017-02-10 20:52
Hi Daniel,

I gave it a go and it seems to be working fine.

<img width="221" alt="screen shot 2017-02-10 at 21 51 40" src="https://cloud.githubusercontent.com/assets/1088217/22843723/1fc0d348-efdb-11e6-9d09-44f4732dd31f.png">

```swift
func test367() {
    let dataStack = Helper.dataStackWithModelName("367")
    let changes: [[String : Any]] = [["id": 1, "first_name": "Daniel", "timestamp": 1486756142]]

    Sync.changes(changes, inEntityNamed: "User", dataStack: dataStack, completion: nil)
    XCTAssertEqual(Helper.countForEntity("User", inContext: dataStack.mainContext), 1)

    dataStack.drop()
}
```

**Comment by 3lvis** [comment] 2017-02-10 20:53
https://github.com/SyncDB/Sync/pull/369

**Comment by dneykov** [comment] 2017-02-10 21:02
That is strange. I will give it another shot next week. Thanks for quick replies.

**Comment by 3lvis** [comment] 2017-02-10 21:05
No worries, looking forward to see what was the issue. Have a great weekend!

**Comment by 3lvis** [comment] 2017-03-08 00:34
Closing this for now. Let me know if you need any other feedback.

**Closed by 3lvis** 2017-03-08 00:34 UTC
