### ISSUE TITLE
Many-to-Many Sync Issue

### ISSUE THREAD

**Issue by padlocked17** [SyncDB/Sync#375] opened 2017-02-28 18:38 UTC
I'm running into an issue where I can't get Sync to recognize or build relationships between Many-to_many Tables.

My JSON looks like the following where "id" of 4865 is the main post and contains a to-many relationship with "custom_meta.wpfc_series" 

    [
      {
        "id": 4865,
        "title": {
          "rendered": "Significant Trouble Part I"
            },
        "custom_meta": {
          "wpfc_speaker”: [
            {
              "term_id": 1107,
              "name": “Speaker Name Here”,
              "description": ""
            }
          ],
          "wpfc_series": [
            {
              "term_id": 584,
              "name": "Significant Trouble",
              "description": ""
            },
            {
              "term_id": 5,
              "name": "Issues to discuss",
              "description": ""
            }
          ]
        }
      }
    ]

I am calling sync via 

    dataStack.performInNewBackgroundContext() { moc in
            ValueTransformer.setValueTransformer(BadAPIValueTransformer(), forName: NSValueTransformerName(rawValue: "BadAPIValueTransformer"))
            Sync.changes(data, inEntityNamed: "Speeches", predicate: nil, parent: nil, parentRelationship: nil, inContext: moc, operations: [.Insert, .Update], completion: nil)
            do {
                try moc.save()
            } catch {
                let nserror = error as NSError
                fatalError("Unresolved error \(nserror), \(nserror.userInfo)")
            }    
        }

My CoreData is setup with my Speeches table and has a relationship to the Series Table.

Speeches has a relationship of type "to-many" with the destination to the Series table and inverse of Speeches set.  It also has 
`hyper.remoteKey = custom_meta.wpfc_series `

![Image of CD](http://i64.tinypic.com/2rdujwi.jpg)

When I sync, I don't get any of the series data populated in Core Data nor does anything even show up for a column of "Series" in the "Speeches" table.  What on earth am I doing wrong?

I know that I had to use the BadAPIValueTransformer for fields that were placed in an array.  But I would think that relationships should be in an array and that is how they are being shown on the Sync page.  I'm at a complete loss.

1. Is the issue that the relationship is nested and not at the top level of the JSON?
2. Should the value for the "hyper.remoteKey" be something different?

**Comment by teripaquitinho** [comment] 2017-03-02 16:38
check here https://github.com/SyncDB/Sync/issues/373, might be helpful.

**Comment by padlocked17** [comment] 2017-03-04 22:54
Thanks @teripaquitinho .  I looked at your write-up and unfortunately, I've already got mine set to integers.

Unfortunately I can't even get a single relationship to exist.

**Comment by 3lvis** [comment] 2017-03-20 22:20
The issue is most likely that deep mapping, meaning using "custom_meta.wpfc_series" for relationships is not very well supported in Sync. We did the work for attributes not for relationships.

**Comment by 3lvis** [comment] 2017-03-20 23:05
@padlocked17 Should be fixed now

**Closed** 2017-03-20 23:05 UTC
