### ISSUE TITLE
operations: [.Insert] is inserting a set of duplicate data

### ISSUE THREAD

**Issue by Pyroscout** [SyncDB/Sync#232] opened 2016-06-18 21:06 UTC
I noticed that .Insert was inserting duplicate data and figured I must be doing something wrong so I called

`Sync.changes(JSON, inEntityNamed: entity, dataStack: self.dataStack, operations: [.Insert], completion: { error in
})`

twice in a row to ensure that it is on the same data and sure enough my entity contains twice the amount of data.
After some continued testing it appears that .Insert only adds one set of duplicate data.

I am not sure if calling it twice in a row causes something weird to happen but i have also done tests where I download the same data from a database two separate times calling insert on both and having twice as much data as i should in my Entity

I really love the simplicity of this framework compared to how CoreData is usually handled. Great job so far!

**Comment by Pyroscout** [comment] 2016-06-22 22:21
@3lvis do you know if this is correct or if I am just doing something wrong?

**Comment by 3lvis** [comment] 2016-06-22 23:43
@Pyroscout Hi! We don't support calling Sync for the same resource at the same time, unexpected behavior is bound to happen. You can either find a way to only call Sync for a resource once at the time, or you can use a NSOperationQueue with maxConcurrentOperationCount = 1.

```swift
let queue = NSOperationQueue()
let operation = Sync(changes: users, inEntityNamed: "User", predicate: nil, dataStack: dataStack)
queue.addOperation(operation)
```

In that way a sync will only be called when the previous one has finished.

**Comment by Pyroscout** [comment] 2016-06-23 02:27
@3lvis Thanks for your quick response! 
I made sure that the first Sync was completed before the second call was made and the information is still being inserted twice. I am using `NSNotificationCenter` to track changes. Here is what is being called the first time:
```NSNotificationCenter.defaultCenter().addObserver(self, selector: #selector(Networking.changeNotification(_:)), name: NSManagedObjectContextObjectsDidChangeNotification, object: self.dataStack.mainContext)
                    Sync.changes(JSON, inEntityNamed: entity, dataStack: self.dataStack, operations: [.All], completion: { error in
                        NSNotificationCenter.defaultCenter().removeObserver(self, name: NSManagedObjectContextObjectsDidChangeNotification, object: nil)
})```

And here is the second call:
```NSNotificationCenter.defaultCenter().addObserver(self, selector: #selector(Networking.changeNotification(_:)), name: NSManagedObjectContextObjectsDidChangeNotification, object: self.dataStack.mainContext)
                    Sync.changes(JSON, inEntityNamed: entity, dataStack: self.dataStack, operations: [.Insert], completion: { error in
                        NSNotificationCenter.defaultCenter().removeObserver(self, name: NSManagedObjectContextObjectsDidChangeNotification, object: nil)
                    })```
JSON contains the same data both times
Any other ideas?

**Comment by 3lvis** [comment] 2016-06-23 02:46
Hi @Pyroscout, 

I added a unit test to verify this, and everything is working as expected. https://github.com/hyperoslo/Sync/pull/235

I be able to follow up on this, could you please share your Core Data model and an example of your JSON?

I have the suspicion that it might be related to changing primary keys.

**Comment by Pyroscout** [comment] 2016-06-23 03:21
I went home for the day a bit ago so I will get those to you tomorrow. How would you like me to give you that information though? Im pretty new to github so I dont know what the best way is

**Comment by 3lvis** [comment] 2016-06-23 03:22
Check this GitHub issue, if has an screenshot of the Core Data model and the JSON file.

https://github.com/hyperoslo/Sync/issues/184

**Comment by Pyroscout** [comment] 2016-06-23 20:56
Here is the Core Data model and the example of my JSON

![screen shot 2016-06-23 at 2 46 10 pm](https://cloud.githubusercontent.com/assets/4473004/16319917/71311444-3952-11e6-87ae-22fd3bc0ae5c.png)
![screen shot 2016-06-23 at 2 49 32 pm](https://cloud.githubusercontent.com/assets/4473004/16319922/747172a2-3952-11e6-8030-06dac448bbcc.png)

**Comment by 3lvis** [comment] 2016-06-23 21:03
Is `postid` the primary key?

**Comment by Pyroscout** [comment] 2016-06-23 21:04
Yes

**Comment by osmarogo** [comment] 2016-06-29 19:42
Hi everyone.

I'm facing a similar issue with my sync process.

After some testing, I noticed that SyncDemoApp has a primary key defined as String type, the model I am working on has a primary Key defined as NSNumber.

I've changed the primary key in my model as String type, after that, the process works as expected.

**Comment by Pyroscout** [comment] 2016-06-29 20:32
All of my keys are Strings so that definitely is not what is wrong with mine. Thanks anyway

**Comment by 3lvis** [comment] 2016-11-30 22:57
I'm not able to reproduce this error, having a sample project would help a lot. Closing until receiving further instructions.

**Closed by 3lvis** 2016-11-30 22:57 UTC
