### ISSUE TITLE
One / Many Nested Relationships Do No Clear When Null

### ISSUE THREAD

**Issue by rlester** [SyncDB/Sync#228] opened 2016-06-03 23:29 UTC
First off thanks for the library its been a huge time saver. I really appreciate the great work everyone has been doing with Sync.

I read in the documentation that if you want to delete a nested relationship you need to return the object's primary key as null. 

> Also if you want to remove all the notes from a user, just provide "notes_ids": null and Sync will do the clean up for you.

I have a case where I return null for the fully nested object and wanted to confirm that isn't a feature.
This example is with the sync operations of .All.

Example:

First sync:

```
{
  "room" : {
    "id": 1,
    "cart": {
      "id": 1,
      "state": "started"
    }
  }
}
```

Now there is a room with one cart.

Second Sync:

```
{
  "room" : {
    "id": 1,
    "cart": null
  }
}
```

Now there is still one room with one cart (this is what I believe the current functionality is). The desired functionality at least for me would be to have one room with a nil cart. 

I believe I have a solution for it and would like to clean it up and open a PR. But I wanted to verify first this isn't current functionality and second is the general desired functionality.

What I have done is I added:

```
    if dictionary[relationshipName] is NSNull {
      if let _ = valueForKey(relationshipName) {
        setValue(nil, forKey: relationshipName)
      }
    }
```

Here: https://github.com/hyperoslo/Sync/blob/master/Source/NSManagedObject%2BSync.swift#L217

**Comment by xTheRamon** [comment] 2016-06-09 19:08
I think this is a duplicate of #225. Please correct me if I'm wrong.

**Comment by 3lvis** [comment] 2016-06-09 19:11
It's a similar issue. I have started looking into it here: 

https://github.com/hyperoslo/Sync/pull/229

**Comment by 3lvis** [comment] 2016-10-24 23:46
This should be fixed as far as I know.

**Closed by 3lvis** 2016-10-24 23:46 UTC

**Comment by tboetig** [comment] 2016-11-02 13:19
Which release did this fix make it into? Does it require updating to v2 ?

**Comment by 3lvis** [comment] 2016-11-02 13:28
Hi @tboetig for what I can see it was part of 1.13.1 https://github.com/SyncDB/Sync/issues/225#issuecomment-242726492
